version: '3'

services: 
    backend:
        build:
            context: ./server
            dockerfile: server/Dockerfile
        image: "server"
        ports: 
            - "3000:3000"
    # frontend: 
    #     build:
    #         context: ./client
    #         dockerfile: client/Dockerfile
    #     image: "client"
    #     ports: 
    #         - "8000:8000"