apiVersion: apps/v1
kind: Deployment
metadata:
  name: kursressourcen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kursressourcen
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kursressourcen
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: kursressourcen
        image: sgse2021containerregistry.azurecr.io/kursressourcen:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kursressourcen
spec:
  ports:
  - port: 8080
  selector:
    app: kursressourcen
