apiVersion: apps/v1
kind: Deployment
metadata:
  name: kursressourcen-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kursressourcen-frontend

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kursressourcen-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: kursressourcen-frontend
        image: sgse2021cr.azurecr.io/kursressourcen_frontend:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kursressourcen-frontend
spec:
  ports:
  - port: 8000
  selector:
    app: kursressourcen-frontend
