apiVersion: apps/v1
kind: Deployment
metadata:
  name: kursressourcen-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kursressourcen-backend 

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kursressourcen-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: kursressourcen-backend
        image: sgse2021containerregistry.azurecr.io/kursressourcen_backend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kursressourcen-backend
spec:
  ports:
  - port: 3000
  selector:
    app: kursressourcen-backend
